import tkinter as tk
from tkinter import ttk, messagebox, scrolledtext, filedialog
import paramiko
import os
import threading
import time
import random
import tempfile
import shutil
import zipfile
import json
import re


class _SimpleVar:
    """Lightweight StringVar substitute for headless/testing mode."""

    def __init__(self, value=""):
        self._value = value
        self._trace_cbs = []

    def get(self):
        return self._value

    def set(self, value):
        self._value = value
        for cb in self._trace_cbs:
            cb(None, None, "write")

    def trace_add(self, mode, callback):
        if mode == "write":
            self._trace_cbs.append(callback)
        return str(id(callback))

    def trace_remove(self, mode, cbname):
        self._trace_cbs = [
            cb for cb in self._trace_cbs if str(id(cb)) != cbname]


class _ToolTip:
    """Lightweight hover tooltip for any widget."""

    def __init__(self, widget, text):
        self.widget = widget
        self.text = text
        self.tip_window = None
        widget.bind("<Enter>", self._show)
        widget.bind("<Leave>", self._hide)

    def _show(self, event=None):
        if self.tip_window:
            return
        x = self.widget.winfo_rootx() + 20
        y = self.widget.winfo_rooty() + self.widget.winfo_height() + 5
        self.tip_window = tw = tk.Toplevel(self.widget)
        tw.wm_overrideredirect(True)
        tw.wm_geometry(f"+{x}+{y}")
        tk.Label(tw, text=self.text, justify=tk.LEFT,
                 background="#1A1A2E", foreground="#E0E0E0",
                 relief=tk.SOLID, borderwidth=1,
                 font=("Consolas", 9), wraplength=300,
                 padx=6, pady=4).pack()

    def _hide(self, event=None):
        if self.tip_window:
            self.tip_window.destroy()
            self.tip_window = None


VARIABLE_DEFAULTS = {
    "ssh_host": "", "ssh_port": "22", "ssh_username": "", "ssh_password": "",
    "ssh_keyfile": "",
    "installation_status": "Not Started",
    "sitename": "", "port": "2010", "device": "/dev/sda1",
    "router": "n", "pasv_addr": "", "pasv_ports": "6000-7000",
    "channelnr": "2",
    "channame1": "#main n nopass", "channame2": "#flood y testing",
    "announcechannels": "#main #flood", "channelops": "#main",
    "chanpass1": "", "chanpass2": "",
    "ircnickname": "l337", "ircserver": "irc.example.com", "ircport": "6667",
    "ircident": "glftpd", "ircrealname": "glFTPd Site Bot",
    "ircpass": "", "ircssl": "0",
    "sections": "3",
    "eur0presystem": "n", "slvprebw": "n", "ircadmin": "n",
    "request": "n", "trial": "n", "vacation": "n",
    "whereami": "n", "precheck": "n", "autonuke": "n",
    "psxcimdb": "n", "psxcimdbchan": "#main",
    "addip": "n", "top": "n", "ircnick": "n",
    "archiver": "n", "section_traffic": "n",
    "admin_username": "admin", "admin_password": "password",
    "admin_ip": "*@192.168.1.*",
}

DEFAULT_SECTIONS = [
    {"name": "MP3", "path": "/site/MP3", "dated": "n"},
    {"name": "0DAY", "path": "/site/0DAY", "dated": "n"},
    {"name": "TV", "path": "/site/TV", "dated": "n"},
]

SCRIPT_VARS = [
    "eur0presystem", "slvprebw", "ircadmin", "request", "trial",
    "vacation", "whereami", "precheck", "autonuke", "psxcimdb",
    "addip", "top", "ircnick", "archiver", "section_traffic",
]

_SECTIONS_MARKER = "__DYNAMIC_SECTIONS__"

# Schema for install.cache generation.
# 1-tuples are raw lines (comments/blanks); 3-tuples are (cache_key, attr, comment).
# The _SECTIONS_MARKER sentinel triggers dynamic section output.
CACHE_SCHEMA = [
    ("# GLFTPD Unattended Installation Configuration",),
    ("# Generated by GLFTPD Installer GUI",),
    ("",),
    ("sitename", "sitename", "Name of the site. Don't use space in sitename."),
    ("port", "port", "Port for the FTP"),
    ("device", "device", "What device to use for /site"),
    ("",),
    ("# Router Configuration",),
    ("router", "router", "If site is behind router"),
    ("pasv_addr", "pasv_addr", "IP or DNS to use as passive address for glFTPd"),
    ("pasv_ports", "pasv_ports", "Port range to use for passive mode for glFTPd"),
    ("",),
    ("# Channel Configuration",),
    ("channelnr", "channelnr", "How many channels the bot will be in"),
    ("channame1", "channame1", "Channelname of 1st chan"),
    ("channame2", "channame2", "Channelname of 2nd chan"),
    ("chanpass1", "chanpass1", "Password for channel 1"),
    ("chanpass2", "chanpass2", "Password for channel 2"),
    ("announcechannels", "announcechannels", "Announce channels"),
    ("channelops", "channelops", "Ops channel"),
    ("",),
    ("# IRC Configuration",),
    ("ircnickname", "ircnickname", "Irc nickname of bot owner"),
    ("ircserver", "ircserver", "IRC server"),
    ("ircport", "ircport", "IRC port"),
    ("ircpass", "ircpass", "IRC password"),
    ("ircssl", "ircssl", "IRC SSL"),
    ("ircident", "ircident", "IRC ident"),
    ("ircrealname", "ircrealname", "IRC realname"),
    ("",),
    ("# Section Configuration",),
    ("sections", "sections",
     "How many sections will be created, max 22 sections allowed"),
    (_SECTIONS_MARKER,),
    ("",),
    ("# Optional Scripts",),
    ("eur0presystem", "eur0presystem", "Install Eur0-pre-system with foo-pre"),
    ("slvprebw", "slvprebw", "Install Slv-PreBW"),
    ("ircadmin", "ircadmin", "Install Tur-Ircadmin"),
    ("request", "request", "Install Tur-Request"),
    ("trial", "trial", "Install Tur-Trial"),
    ("vacation", "vacation", "Install Tur-Vacation"),
    ("whereami", "whereami", "Install Whereami"),
    ("precheck", "precheck", "Install Precheck"),
    ("autonuke", "autonuke", "Install Tur-Autonuke"),
    ("psxcimdb", "psxcimdb", "Install PSXC-IMDB"),
    ("psxcimdbchan", "psxcimdbchan", "Trigger chan for PSXC-IMDB"),
    ("addip", "addip", "Install Tur-Addip"),
    ("top", "top", "Install Top"),
    ("ircnick", "ircnick", "Install Ircnick"),
    ("archiver", "archiver", "Install Tur-Archiver"),
    ("section_traffic", "section_traffic", "Install Section-Traffic"),
    ("",),
    ("# Administrator Account",),
    ("username", "admin_username", "Username for Administrator account"),
    ("password", "admin_password", "Password for Administrator account"),
    ("ip", "admin_ip", "IP for Administrator account"),
]


class GlftpdInstallerGUI:
    COLORS = {
        "bg": "#0A0A0F",
        "fg": "#00FF9D",
        "error": "#FF2D55",
        "warning": "#FFD700",
        "text": "#E0E0E0",
        "input_bg": "#1A1A1F",
    }

    def __init__(self, root, testing=False):
        self.root = root
        self.testing = testing
        self._init_variables()

        if not testing:
            self._setup_window()
            self._configure_styles()
            self._setup_menu_bar()
            self._setup_status_bar()
            self.setup_gui()
            self._start_matrix_effect()
            self.root.bind("<Control-s>", lambda e: self.save_profile())
            self.root.bind("<Control-o>", lambda e: self.load_profile())

    def _make_var(self, value=""):
        if self.testing:
            return _SimpleVar(value)
        return tk.StringVar(self.root, value=value)

    def _init_variables(self):
        for attr, default in VARIABLE_DEFAULTS.items():
            setattr(self, attr, self._make_var(default))

        self.section_entries = []
        for sec in DEFAULT_SECTIONS:
            self.section_entries.append({
                "name": self._make_var(sec["name"]),
                "path": self._make_var(sec["path"]),
                "dated": self._make_var(sec["dated"]),
            })

        self._suppress_rebuild = False
        self.sections.trace_add("write", self._on_sections_changed)

        self.installation_running = False
        self.current_step = 0
        self.total_steps = 5
        self.matrix_labels = []
        self.ssh_client = None
        self.sftp_client = None
        self._script_cbs = []

    # -- Window & styling -------------------------------------------------------

    def _setup_window(self):
        self.root.title("[GLFTPD INSTALLER]")
        self.root.geometry("900x700")
        self.root.minsize(800, 600)
        self.root.configure(bg=self.COLORS["bg"])
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

    def _configure_styles(self):
        c = self.COLORS
        self.style = ttk.Style()
        self.style.theme_use("clam")

        configs = {
            "TFrame": {"background": c["bg"]},
            "TLabel": {"background": c["bg"], "foreground": c["text"],
                       "font": ("Consolas", 10)},
            "TEntry": {"fieldbackground": c["input_bg"], "foreground": c["fg"],
                       "insertcolor": c["fg"]},
            "TButton": {"background": c["input_bg"], "foreground": c["fg"],
                        "font": ("Consolas", 10, "bold")},
            "TNotebook": {"background": c["bg"], "tabmargins": [2, 5, 2, 0]},
            "TNotebook.Tab": {"background": c["input_bg"],
                              "foreground": c["text"],
                              "padding": [10, 5],
                              "font": ("Consolas", 10, "bold")},
            "TLabelframe": {"background": c["bg"], "foreground": c["fg"]},
            "TLabelframe.Label": {"background": c["bg"], "foreground": c["fg"],
                                  "font": ("Consolas", 10, "bold")},
            "Horizontal.TProgressbar": {"background": c["fg"],
                                        "troughcolor": c["input_bg"]},
        }
        for name, kwargs in configs.items():
            self.style.configure(name, **kwargs)

        self.style.map("TNotebook.Tab",
                       background=[("selected", c["bg"])],
                       foreground=[("selected", c["fg"])])

    def _setup_menu_bar(self):
        c = self.COLORS
        menubar = tk.Menu(self.root, bg=c["input_bg"], fg=c["text"],
                          activebackground=c["fg"], activeforeground=c["bg"],
                          font=("Consolas", 9))

        file_menu = tk.Menu(menubar, tearoff=0, bg=c["input_bg"],
                            fg=c["text"], activebackground=c["fg"],
                            activeforeground=c["bg"], font=("Consolas", 9))
        file_menu.add_command(label="Save Profile  (Ctrl+S)",
                              command=self.save_profile)
        file_menu.add_command(label="Load Profile  (Ctrl+O)",
                              command=self.load_profile)
        file_menu.add_command(label="Import install.cache",
                              command=self.import_cache)
        file_menu.add_separator()
        file_menu.add_command(label="Exit", command=self._on_close)

        menubar.add_cascade(label="File", menu=file_menu)
        self.root.config(menu=menubar)

    def _setup_status_bar(self):
        c = self.COLORS
        self.status_frame = tk.Frame(self.root, bg=c["input_bg"], height=28)
        self.status_frame.pack(side="bottom", fill="x")
        self.status_frame.pack_propagate(False)

        self.status_indicator = tk.Label(
            self.status_frame, text="\u25CF", font=("Consolas", 14),
            bg=c["input_bg"], fg=c["error"])
        self.status_indicator.pack(side="left", padx=(8, 2))

        self.status_label = tk.Label(
            self.status_frame, text="DISCONNECTED",
            font=("Consolas", 9, "bold"),
            bg=c["input_bg"], fg=c["text"])
        self.status_label.pack(side="left")

    def _update_status(self):
        if self.testing:
            return
        c = self.COLORS
        if self.ssh_client:
            host = self.ssh_host.get()
            port = self.ssh_port.get()
            self.status_indicator.config(fg=c["fg"])
            self.status_label.config(
                text=f"CONNECTED  {host}:{port}",
                fg=c["fg"])
        else:
            self.status_indicator.config(fg=c["error"])
            self.status_label.config(text="DISCONNECTED", fg=c["text"])

    # -- GUI layout -------------------------------------------------------------

    def setup_gui(self):
        self.notebook = ttk.Notebook(self.root)
        self.notebook.pack(expand=True, fill="both", padx=10, pady=(10, 5))

        self.connection_frame = ttk.Frame(self.notebook)
        self.installation_frame = ttk.Frame(self.notebook)
        self.log_frame = ttk.Frame(self.notebook)

        self.notebook.add(self.connection_frame, text="[CONNECTION]")
        self.notebook.add(self.installation_frame, text="[INSTALLATION]")
        self.notebook.add(self.log_frame, text="[LOG]")

        self._setup_connection_frame()
        self._setup_installation_frame()
        self._setup_log_frame()

    def _setup_connection_frame(self):
        ssh_frame = ttk.LabelFrame(self.connection_frame,
                                   text="[SSH CONNECTION]", padding=10)
        ssh_frame.pack(fill="x", padx=5, pady=5)

        fields = [
            ("[HOST]:", self.ssh_host, False,
             "Hostname or IP of the remote Linux server"),
            ("[PORT]:", self.ssh_port, False,
             "SSH port (default: 22)"),
            ("[USER]:", self.ssh_username, False,
             "SSH username with sudo privileges"),
            ("[PASS]:", self.ssh_password, True,
             "SSH password (or leave blank for key auth)"),
        ]
        for row, (label, var, is_pw, tip) in enumerate(fields):
            lbl = ttk.Label(ssh_frame, text=label)
            lbl.grid(row=row, column=0, sticky="w", padx=5, pady=2)
            _ToolTip(lbl, tip)
            entry = ttk.Entry(ssh_frame, textvariable=var,
                              show="*" if is_pw else "")
            entry.grid(row=row, column=1, sticky="ew", padx=5, pady=2)
            entry.bind("<Return>", lambda e: self.connect_ssh())

        keyfile_row = len(fields)
        lbl = ttk.Label(ssh_frame, text="[KEY FILE]:")
        lbl.grid(row=keyfile_row, column=0, sticky="w", padx=5, pady=2)
        _ToolTip(lbl, "Optional SSH private key file (PEM/OpenSSH format)")
        keyfile_frame = ttk.Frame(ssh_frame)
        keyfile_frame.grid(row=keyfile_row, column=1, sticky="ew",
                           padx=5, pady=2)
        ttk.Entry(keyfile_frame,
                  textvariable=self.ssh_keyfile).pack(
            side=tk.LEFT, fill="x", expand=True)
        ttk.Button(keyfile_frame, text="[...]",
                   command=self._browse_keyfile,
                   width=4).pack(side=tk.RIGHT, padx=(4, 0))

        ssh_frame.columnconfigure(1, weight=1)

        btn_frame = ttk.Frame(ssh_frame)
        btn_frame.grid(row=keyfile_row + 1, column=0, columnspan=2, pady=10)
        ttk.Button(btn_frame, text="[CONNECT]",
                   command=self.connect_ssh).pack(side=tk.LEFT, padx=5)
        ttk.Button(btn_frame, text="[DISCONNECT]",
                   command=self.disconnect_ssh).pack(side=tk.LEFT, padx=5)

    def _browse_keyfile(self):
        path = filedialog.askopenfilename(
            title="Select SSH Key File",
            filetypes=[("Key files", "*.pem *.key *.pub"),
                       ("All files", "*.*")])
        if path:
            self.ssh_keyfile.set(path)

    def _setup_installation_frame(self):
        install_frame = ttk.LabelFrame(self.installation_frame,
                                       text="[INSTALLATION OPTIONS]",
                                       padding=15)
        install_frame.pack(fill="both", expand=True, padx=5, pady=5)

        canvas = tk.Canvas(install_frame, bg=self.COLORS["bg"],
                           highlightthickness=0)
        scrollbar = ttk.Scrollbar(install_frame, orient="vertical",
                                  command=canvas.yview)
        self._scrollable = scrollable = ttk.Frame(canvas)

        scrollable.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
        canvas.create_window((0, 0), window=scrollable, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        def _on_mousewheel(event):
            canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        canvas.bind("<Enter>",
                    lambda e: canvas.bind_all("<MouseWheel>", _on_mousewheel))
        canvas.bind("<Leave>",
                    lambda e: canvas.unbind_all("<MouseWheel>"))

        row = [0]

        def header(text):
            ttk.Label(scrollable, text=text, font=("Consolas", 12, "bold"),
                      foreground=self.COLORS["fg"]).grid(
                row=row[0], column=0, columnspan=2, pady=15)
            row[0] += 1

        def field(label, var, password=False, tooltip=None):
            lbl = ttk.Label(scrollable, text=label, font=("Consolas", 10))
            lbl.grid(row=row[0], column=0, sticky="w", padx=5, pady=2)
            if tooltip:
                _ToolTip(lbl, tooltip)
            ttk.Entry(scrollable, textvariable=var,
                      show="*" if password else "").grid(
                row=row[0], column=1, sticky="ew", padx=5, pady=2)
            row[0] += 1

        def checkbox(label, var, tooltip=None):
            f = ttk.Frame(scrollable)
            f.grid(row=row[0], column=0, columnspan=2, sticky="w",
                   padx=5, pady=2)
            cb = ttk.Checkbutton(f)
            cb.configure(
                command=lambda v=var: v.set("y" if v.get() == "n" else "n"))
            cb.state(["!alternate",
                       "!selected" if var.get() == "n" else "selected"])
            cb.pack(side=tk.LEFT)
            lbl = ttk.Label(f, text=label, font=("Consolas", 10))
            lbl.pack(side=tk.LEFT, padx=5)
            if tooltip:
                _ToolTip(lbl, tooltip)
            row[0] += 1
            return cb

        # -- Server Config --
        header("[SERVER CONFIG]")
        field("[SITE]:", self.sitename,
              tooltip="Name of the site. Don't use spaces.")
        field("[FTP PORT]:", self.port,
              tooltip="Port for the FTP daemon")
        field("[DEVICE]:", self.device,
              tooltip="Device to use for /site (e.g. /dev/sda1)")

        # -- Router Config --
        header("[ROUTER CONFIG]")
        checkbox("[BEHIND ROUTER]:", self.router,
                 tooltip="Enable if site is behind a NAT router")
        field("[PASSIVE ADDRESS]:", self.pasv_addr,
              tooltip="External IP/DNS for passive FTP connections")
        field("[PASSIVE PORTS]:", self.pasv_ports,
              tooltip="Port range for passive mode (e.g. 6000-7000)")

        # -- Channel Config --
        header("[CHANNEL CONFIG]")
        field("[CHANNELS]:", self.channelnr,
              tooltip="How many IRC channels the bot will join")
        field("[CHAN1]:", self.channame1,
              tooltip="Channel 1: #name flag password")
        field("[CHAN1 PASS]:", self.chanpass1, True,
              tooltip="Password for channel 1")
        field("[CHAN2]:", self.channame2,
              tooltip="Channel 2: #name flag password")
        field("[CHAN2 PASS]:", self.chanpass2, True,
              tooltip="Password for channel 2")
        field("[ANNOUNCE]:", self.announcechannels,
              tooltip="Space-separated list of announce channels")
        field("[OPS]:", self.channelops,
              tooltip="Channel where bot has ops")

        # -- IRC Config --
        header("[IRC CONFIG]")
        field("[NICK]:", self.ircnickname,
              tooltip="IRC nickname of bot owner")
        field("[IRC SERVER]:", self.ircserver,
              tooltip="IRC server hostname")
        field("[IRC PORT]:", self.ircport,
              tooltip="IRC server port")
        field("[IRC PASS]:", self.ircpass, True,
              tooltip="IRC server password (if required)")
        field("[IRC SSL]:", self.ircssl,
              tooltip="Use SSL for IRC (0=no, 1=yes)")
        field("[IRC IDENT]:", self.ircident,
              tooltip="IRC ident string")
        field("[IRC REALNAME]:", self.ircrealname,
              tooltip="IRC realname field")

        # -- Section Config (dynamic) --
        header("[SECTION CONFIG]")
        field("[SECTIONS (1-22)]:", self.sections,
              tooltip="Number of sections (1-22). "
                      "UI updates when you change this value.")

        self._section_frame = ttk.Frame(scrollable)
        self._section_frame.grid(row=row[0], column=0, columnspan=2,
                                 sticky="ew", padx=5)
        row[0] += 1
        self._rebuild_sections()

        # -- Optional Scripts --
        header("[OPTIONAL SCRIPTS]")

        scripts_btn_frame = ttk.Frame(scrollable)
        scripts_btn_frame.grid(row=row[0], column=0, columnspan=2,
                               sticky="w", padx=5, pady=(0, 5))
        ttk.Button(scripts_btn_frame, text="[SELECT ALL]",
                   command=self._select_all_scripts).pack(
            side=tk.LEFT, padx=2)
        ttk.Button(scripts_btn_frame, text="[DESELECT ALL]",
                   command=self._deselect_all_scripts).pack(
            side=tk.LEFT, padx=2)
        row[0] += 1

        self._script_cbs = []
        self._script_cbs.append(
            checkbox("[EUR0 PRE SYSTEM]:", self.eur0presystem,
                     tooltip="Install Eur0-pre-system with foo-pre"))
        self._script_cbs.append(
            checkbox("[SLV-PREBW]:", self.slvprebw,
                     tooltip="Install Slv-PreBW"))
        self._script_cbs.append(
            checkbox("[TUR-IRCADMIN]:", self.ircadmin,
                     tooltip="Install Tur-Ircadmin"))
        self._script_cbs.append(
            checkbox("[TUR-REQUEST]:", self.request,
                     tooltip="Install Tur-Request"))
        self._script_cbs.append(
            checkbox("[TUR-TRIAL]:", self.trial,
                     tooltip="Install Tur-Trial"))
        self._script_cbs.append(
            checkbox("[TUR-VACATION]:", self.vacation,
                     tooltip="Install Tur-Vacation"))
        self._script_cbs.append(
            checkbox("[WHEREAMI]:", self.whereami,
                     tooltip="Install Whereami"))
        self._script_cbs.append(
            checkbox("[PRECHECK]:", self.precheck,
                     tooltip="Install Precheck"))
        self._script_cbs.append(
            checkbox("[TUR-AUTONUKE]:", self.autonuke,
                     tooltip="Install Tur-Autonuke"))
        self._script_cbs.append(
            checkbox("[PSXC-IMDB]:", self.psxcimdb,
                     tooltip="Install PSXC-IMDB"))
        field("[PSXC-IMDB CHAN]:", self.psxcimdbchan,
              tooltip="Trigger channel for PSXC-IMDB")
        self._script_cbs.append(
            checkbox("[TUR-ADDIP]:", self.addip,
                     tooltip="Install Tur-Addip"))
        self._script_cbs.append(
            checkbox("[TOP]:", self.top,
                     tooltip="Install Top"))
        self._script_cbs.append(
            checkbox("[IRCNICK]:", self.ircnick,
                     tooltip="Install Ircnick"))
        self._script_cbs.append(
            checkbox("[TUR-ARCHIVER]:", self.archiver,
                     tooltip="Install Tur-Archiver"))
        self._script_cbs.append(
            checkbox("[SECTION-TRAFFIC]:", self.section_traffic,
                     tooltip="Install Section-Traffic"))

        # -- Admin Account --
        header("[ADMIN ACCOUNT]")
        field("[USERNAME]:", self.admin_username,
              tooltip="Username for the administrator account")
        field("[PASSWORD]:", self.admin_password, True,
              tooltip="Password for the administrator account")
        field("[IP]:", self.admin_ip,
              tooltip="IP mask for admin (e.g. *@192.168.1.*)")

        # -- Export / Install --
        header("[ACTIONS]")
        export_frame = ttk.Frame(scrollable)
        export_frame.grid(row=row[0], column=0, columnspan=2, sticky="ew",
                          pady=10)
        ttk.Button(export_frame, text="[EXPORT UNATTENDED CONFIG]",
                   command=self.export_unattended_config).pack(
            side=tk.LEFT, padx=5)
        ttk.Button(export_frame, text="[EXPORT OFFLINE INSTALLER]",
                   command=self.export_offline_installer).pack(
            side=tk.RIGHT, padx=5)
        row[0] += 1

        self.install_button = ttk.Button(
            scrollable, text="[START INSTALLATION]",
            command=self.start_installation)
        self.install_button.grid(row=row[0], column=0, columnspan=2, pady=15)

        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

    # -- Dynamic sections -------------------------------------------------------

    def _on_sections_changed(self, *args):
        if self._suppress_rebuild:
            return
        self._rebuild_sections()

    def _rebuild_sections(self):
        try:
            count = int(self.sections.get())
            count = max(1, min(22, count))
        except (ValueError, TypeError):
            return

        while len(self.section_entries) < count:
            self.section_entries.append({
                "name": self._make_var(""),
                "path": self._make_var("/site/"),
                "dated": self._make_var("n"),
            })
        self.section_entries = self.section_entries[:count]

        if self.testing or not hasattr(self, "_section_frame"):
            return

        for widget in self._section_frame.winfo_children():
            widget.destroy()

        for i, sec in enumerate(self.section_entries):
            num = i + 1
            r = i * 3

            ttk.Label(self._section_frame, text=f"[SECTION{num}]:",
                      font=("Consolas", 10)).grid(
                row=r, column=0, sticky="w", padx=5, pady=2)
            ttk.Entry(self._section_frame,
                      textvariable=sec["name"]).grid(
                row=r, column=1, sticky="ew", padx=5, pady=2)

            f = ttk.Frame(self._section_frame)
            f.grid(row=r + 1, column=0, columnspan=2, sticky="w",
                   padx=5, pady=2)
            cb = ttk.Checkbutton(f)
            cb.configure(command=lambda v=sec["dated"]:
                         v.set("y" if v.get() == "n" else "n"))
            cb.state(["!alternate",
                       "!selected" if sec["dated"].get() == "n"
                       else "selected"])
            cb.pack(side=tk.LEFT)
            ttk.Label(f, text=f"[SECTION{num} DATED]:",
                      font=("Consolas", 10)).pack(side=tk.LEFT, padx=5)

            ttk.Label(self._section_frame, text=f"[SECTION{num} PATH]:",
                      font=("Consolas", 10)).grid(
                row=r + 2, column=0, sticky="w", padx=5, pady=2)
            ttk.Entry(self._section_frame,
                      textvariable=sec["path"]).grid(
                row=r + 2, column=1, sticky="ew", padx=5, pady=2)

    # -- Log frame --------------------------------------------------------------

    def _setup_log_frame(self):
        c = self.COLORS
        log_container = ttk.LabelFrame(self.log_frame,
                                       text="[INSTALLATION LOG]", padding=10)
        log_container.pack(fill="both", expand=True, padx=5, pady=5)

        toolbar = ttk.Frame(log_container)
        toolbar.pack(fill="x", pady=(0, 5))

        ttk.Button(toolbar, text="[CLEAR LOG]",
                   command=self.clear_log).pack(side=tk.LEFT, padx=5)
        ttk.Button(toolbar, text="[EXPORT LOG]",
                   command=self.export_log).pack(side=tk.LEFT, padx=5)

        progress_frame = ttk.Frame(log_container)
        progress_frame.pack(fill="x", pady=(0, 5))

        self.progress_label = ttk.Label(progress_frame, text="[READY]",
                                        font=("Consolas", 10, "bold"))
        self.progress_label.pack(side="left", padx=5)

        self.progress_bar = ttk.Progressbar(
            progress_frame, mode="determinate", length=300,
            style="Horizontal.TProgressbar")
        self.progress_bar.pack(side="right", padx=5)

        self.log_text = scrolledtext.ScrolledText(
            log_container, height=20, font=("Consolas", 10),
            bg=c["bg"], fg=c["text"],
            insertbackground=c["fg"],
            selectbackground=c["fg"], selectforeground=c["bg"])
        self.log_text.pack(fill="both", expand=True)

        self.log_text.tag_configure("timestamp", foreground=c["fg"])
        self.log_text.tag_configure("error", foreground=c["error"])
        self.log_text.tag_configure("success", foreground=c["fg"])
        self.log_text.tag_configure("warning", foreground=c["warning"])

    # -- Matrix effect ----------------------------------------------------------

    def _start_matrix_effect(self):
        c = self.COLORS
        self._matrix_active = True
        self.root.bind("<FocusIn>", self._on_focus_in)
        self.root.bind("<FocusOut>", self._on_focus_out)
        for _ in range(30):
            lbl = tk.Label(self.root, text="", font=("Consolas", 8),
                           bg=c["bg"], fg=c["fg"])
            lbl.place(x=random.randint(0, 880), y=random.randint(-100, 0))
            self.matrix_labels.append(lbl)
        self._update_matrix()

    def _on_focus_in(self, event=None):
        if not self._matrix_active:
            self._matrix_active = True
            self._update_matrix()

    def _on_focus_out(self, event=None):
        self._matrix_active = False

    def _update_matrix(self):
        if not self._matrix_active:
            return
        for lbl in self.matrix_labels:
            if random.random() < 0.15:
                lbl.config(text=random.choice("01"))
            y = lbl.winfo_y()
            if y > 700:
                lbl.place(x=random.randint(0, 880), y=-20)
            else:
                lbl.place(x=lbl.winfo_x(), y=y + 8)
        self.root.after(100, self._update_matrix)

    # -- SSH connection ---------------------------------------------------------

    def connect_ssh(self):
        host = self.ssh_host.get().strip()
        if not host:
            messagebox.showerror("Error", "Please enter a hostname")
            return

        try:
            port = int(self.ssh_port.get())
        except ValueError:
            messagebox.showerror("Error", "SSH port must be a number")
            return

        username = self.ssh_username.get().strip()
        if not username:
            messagebox.showerror("Error", "Please enter a username")
            return

        self.disconnect_ssh()

        try:
            self.ssh_client = paramiko.SSHClient()
            self.ssh_client.load_system_host_keys()
            self.ssh_client.set_missing_host_key_policy(
                paramiko.WarningPolicy())

            connect_kw = {
                "hostname": host, "port": port,
                "username": username, "timeout": 10,
            }
            keyfile = self.ssh_keyfile.get().strip()
            if keyfile and os.path.isfile(keyfile):
                connect_kw["key_filename"] = keyfile
            if self.ssh_password.get():
                connect_kw["password"] = self.ssh_password.get()

            self.ssh_client.connect(**connect_kw)
            self.sftp_client = self.ssh_client.open_sftp()
            self.log_message("SSH connection established successfully!",
                             "success")
        except Exception as e:
            self.ssh_client = None
            self.log_message(f"Failed to connect: {e}", "error")
            messagebox.showerror("Error", f"Failed to connect: {e}")

        self._update_status()

    def disconnect_ssh(self):
        for client in (self.sftp_client, self.ssh_client):
            if client:
                try:
                    client.close()
                except Exception:
                    pass
        self.sftp_client = None
        self.ssh_client = None
        self._update_status()

    def _on_close(self):
        self.disconnect_ssh()
        self.root.destroy()

    # -- Logging & progress (thread-safe via root.after) ------------------------

    def log_message(self, message, tag=None):
        if self.testing:
            return
        self.root.after(0, self._log_message_impl, message, tag)

    def _log_message_impl(self, message, tag):
        timestamp = time.strftime("%H:%M:%S")
        self.log_text.insert(tk.END, f"[{timestamp}] ", "timestamp")
        self.log_text.insert(tk.END, f"{message}\n", tag)
        self.log_text.see(tk.END)

    def update_progress(self, step, message):
        if self.testing:
            return
        self.root.after(0, self._update_progress_impl, step, message)

    def _update_progress_impl(self, step, message):
        self.current_step = step
        progress = (step / self.total_steps) * 100
        self.progress_bar["value"] = progress
        self.progress_label["text"] = f"[{message}]"
        self.root.update_idletasks()

    def clear_log(self):
        if self.testing:
            return
        self.log_text.delete("1.0", tk.END)

    def export_log(self):
        if self.testing:
            return
        path = filedialog.asksaveasfilename(
            defaultextension=".log",
            filetypes=[("Log files", "*.log"), ("Text files", "*.txt"),
                       ("All files", "*.*")],
            title="Export Installation Log")
        if not path:
            return
        try:
            with open(path, "w") as f:
                f.write(self.log_text.get("1.0", tk.END))
            self.log_message(f"Log exported to {path}", "success")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to export log: {e}")

    # -- Script toggles ---------------------------------------------------------

    def _select_all_scripts(self):
        for name in SCRIPT_VARS:
            getattr(self, name).set("y")
        if not self.testing:
            for cb in self._script_cbs:
                cb.state(["selected"])

    def _deselect_all_scripts(self):
        for name in SCRIPT_VARS:
            getattr(self, name).set("n")
        if not self.testing:
            for cb in self._script_cbs:
                cb.state(["!selected"])

    # -- Profiles & import ------------------------------------------------------

    def save_profile(self):
        if self.testing:
            return
        path = filedialog.asksaveasfilename(
            defaultextension=".json",
            filetypes=[("JSON profiles", "*.json"), ("All files", "*.*")],
            title="Save Configuration Profile")
        if path:
            try:
                self.save_profile_to(path)
                self.log_message(f"Profile saved to {path}", "success")
            except Exception as e:
                self.log_message(f"Error saving profile: {e}", "error")
                messagebox.showerror("Error",
                                     f"Failed to save profile: {e}")

    def save_profile_to(self, path):
        data = {}
        for attr in VARIABLE_DEFAULTS:
            data[attr] = getattr(self, attr).get()
        data["section_entries"] = [
            {"name": s["name"].get(), "path": s["path"].get(),
             "dated": s["dated"].get()}
            for s in self.section_entries
        ]
        tmp_path = path + ".tmp"
        with open(tmp_path, "w") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp_path, path)

    def load_profile(self):
        if self.testing:
            return
        path = filedialog.askopenfilename(
            filetypes=[("JSON profiles", "*.json"), ("All files", "*.*")],
            title="Load Configuration Profile")
        if path:
            try:
                self.load_profile_from(path)
                self.log_message(f"Profile loaded from {path}", "success")
            except Exception as e:
                self.log_message(f"Error loading profile: {e}", "error")
                messagebox.showerror("Error",
                                     f"Failed to load profile: {e}")

    def load_profile_from(self, path):
        with open(path) as f:
            data = json.load(f)
        self._apply_profile(data)

    def _apply_profile(self, data):
        self._suppress_rebuild = True
        try:
            for attr in VARIABLE_DEFAULTS:
                if attr in data:
                    getattr(self, attr).set(data[attr])

            if "section_entries" in data:
                sec_data = data["section_entries"]
                self.sections.set(str(len(sec_data)))

                while len(self.section_entries) < len(sec_data):
                    self.section_entries.append({
                        "name": self._make_var(""),
                        "path": self._make_var("/site/"),
                        "dated": self._make_var("n"),
                    })
                self.section_entries = self.section_entries[:len(sec_data)]

                for i, entry in enumerate(sec_data):
                    self.section_entries[i]["name"].set(
                        entry.get("name", ""))
                    self.section_entries[i]["path"].set(
                        entry.get("path", ""))
                    self.section_entries[i]["dated"].set(
                        entry.get("dated", "n"))
        finally:
            self._suppress_rebuild = False

        self._rebuild_sections()

    def import_cache(self):
        if self.testing:
            return
        path = filedialog.askopenfilename(
            filetypes=[("Cache files", "*.cache"), ("All files", "*.*")],
            title="Import install.cache")
        if path:
            try:
                self.import_cache_from(path)
                self.log_message(
                    f"Imported configuration from {path}", "success")
            except Exception as e:
                self.log_message(f"Error importing cache: {e}", "error")
                messagebox.showerror("Error",
                                     f"Failed to import cache: {e}")

    def import_cache_from(self, path):
        with open(path) as f:
            content = f.read()
        self._parse_cache(content)

    def _parse_cache(self, content):
        kv_re = re.compile(r'^(\w+)="((?:[^"\\]|\\.)*)"', re.MULTILINE)
        data = dict(kv_re.findall(content))

        cache_to_attr = {}
        for entry in CACHE_SCHEMA:
            if len(entry) == 3:
                cache_key, attr, _ = entry
                cache_to_attr[cache_key] = attr

        self._suppress_rebuild = True
        try:
            for cache_key, value in data.items():
                if cache_key in cache_to_attr:
                    getattr(self, cache_to_attr[cache_key]).set(value)

            sec_count = int(data.get("sections", "3"))
            self.sections.set(str(sec_count))

            while len(self.section_entries) < sec_count:
                self.section_entries.append({
                    "name": self._make_var(""),
                    "path": self._make_var("/site/"),
                    "dated": self._make_var("n"),
                })
            self.section_entries = self.section_entries[:sec_count]

            sec_name_re = re.compile(r"^section(\d+)$")
            sec_dated_re = re.compile(r"^section(\d+)dated$")
            sec_path_re = re.compile(r"^sectionpath(\d+)$")

            for key, value in data.items():
                for pattern, field_key in [
                    (sec_name_re, "name"),
                    (sec_dated_re, "dated"),
                    (sec_path_re, "path"),
                ]:
                    m = pattern.match(key)
                    if m:
                        idx = int(m.group(1)) - 1
                        if 0 <= idx < len(self.section_entries):
                            self.section_entries[idx][field_key].set(value)
                        break
        finally:
            self._suppress_rebuild = False

        self._rebuild_sections()

    # -- Installation -----------------------------------------------------------

    def start_installation(self):
        if self.testing:
            return
        if not self.ssh_client:
            messagebox.showerror("Error",
                                 "Please establish SSH connection first!")
            return
        if self.installation_running:
            return
        if not self.sitename.get().strip():
            messagebox.showerror("Error", "Please enter a site name")
            return

        host = self.ssh_host.get()
        if not messagebox.askyesno(
                "Confirm Installation",
                f"Install glFTPd on {host}?\n\n"
                "This will modify the remote server."):
            return

        self.installation_running = True
        self.install_button["state"] = "disabled"
        self.progress_bar["value"] = 0
        self.current_step = 0

        self.notebook.select(self.log_frame)

        thread = threading.Thread(target=self._run_installation, daemon=True)
        thread.start()

    def _check_ssh_alive(self):
        transport = self.ssh_client.get_transport() if self.ssh_client else None
        if not transport or not transport.is_active():
            raise ConnectionError("SSH connection lost")

    def _exec_checked(self, cmd, timeout=30):
        self._check_ssh_alive()
        stdin, stdout, stderr = self.ssh_client.exec_command(
            cmd, timeout=timeout)
        exit_code = stdout.channel.recv_exit_status()
        out = stdout.read().decode(errors="replace")
        err = stderr.read().decode(errors="replace")
        return exit_code, out, err

    def _run_installation(self):
        remote_path = "/tmp/glftpd-installer"
        install_ok = False
        try:
            self.update_progress(1, "CREATING DIR")
            code, _, err = self._exec_checked(f"mkdir -p {remote_path}")
            if code != 0:
                raise RuntimeError(
                    f"Failed to create remote directory: {err}")
            self.log_message("Created installation directory")

            self.update_progress(2, "TRANSFERRING")
            self._check_ssh_alive()
            local_path = os.path.dirname(os.path.abspath(__file__))
            self.sftp_client.put(
                os.path.join(local_path, "install.sh"),
                f"{remote_path}/install.sh")
            self.log_message("Transferred installation script")

            cache_content = self.generate_cache_content()
            with tempfile.NamedTemporaryFile(
                    mode="w", suffix=".cache", delete=False) as tmp:
                tmp.write(cache_content)
                tmp_path = tmp.name
            try:
                self._check_ssh_alive()
                self.sftp_client.put(tmp_path,
                                     f"{remote_path}/install.cache")
            finally:
                os.unlink(tmp_path)
            self.log_message("Transferred configuration file")

            self.update_progress(3, "SETTING UP")
            code, _, err = self._exec_checked(
                f"chmod +x {remote_path}/install.sh")
            if code != 0:
                raise RuntimeError(f"Failed to chmod install.sh: {err}")
            self.log_message("Made installation script executable")

            self.update_progress(4, "INSTALLING")
            self._check_ssh_alive()
            stdin, stdout, stderr = self.ssh_client.exec_command(
                f"sudo -S {remote_path}/install.sh")
            stdin.write(self.ssh_password.get() + "\n")
            stdin.flush()

            channel = stdout.channel
            channel.settimeout(600)
            buf_out = b""
            buf_err = b""
            while not channel.exit_status_ready():
                if channel.recv_ready():
                    chunk = channel.recv(4096)
                    buf_out += chunk
                    while b"\n" in buf_out:
                        line, buf_out = buf_out.split(b"\n", 1)
                        self.log_message(
                            line.decode(errors="replace").rstrip())
                if channel.recv_stderr_ready():
                    buf_err += channel.recv_stderr(4096)
                time.sleep(0.05)

            while channel.recv_ready():
                buf_out += channel.recv(4096)
            while channel.recv_stderr_ready():
                buf_err += channel.recv_stderr(4096)

            if buf_out:
                for line in buf_out.decode(errors="replace").splitlines():
                    self.log_message(line.rstrip())

            exit_code = channel.recv_exit_status()
            errors = buf_err.decode(errors="replace")
            if errors:
                self.log_message(f"Errors:\n{errors}", "error")

            if exit_code != 0:
                raise RuntimeError(
                    f"install.sh exited with code {exit_code}")

            install_ok = True
            self.update_progress(5, "CLEANING UP")
            self._exec_checked(f"rm -rf {remote_path}")
            self.log_message("Installation completed successfully!",
                             "success")
            self.root.after(0, messagebox.showinfo,
                            "Success", "Installation completed!")

        except Exception as e:
            self.log_message(f"Error during installation: {e}", "error")
            if not install_ok:
                self.log_message(
                    "Remote files kept for debugging at "
                    f"{remote_path}", "warning")
            self.root.after(0, messagebox.showerror,
                            "Error", f"Installation failed: {e}")
        finally:
            self.installation_running = False
            self.root.after(0, self._reset_install_button)

    def _reset_install_button(self):
        self.install_button["state"] = "normal"
        self._update_progress_impl(0, "READY")

    # -- Export -----------------------------------------------------------------

    def export_unattended_config(self):
        if self.testing:
            return
        try:
            save_path = filedialog.asksaveasfilename(
                defaultextension=".cache",
                filetypes=[("Cache files", "*.cache"),
                           ("All files", "*.*")],
                title="Save Unattended Configuration")
            if not save_path:
                return

            with open(save_path, "w") as f:
                f.write(self.generate_cache_content())
            self.log_message(
                f"Unattended configuration exported to {save_path}",
                "success")
        except Exception as e:
            self.log_message(f"Error exporting configuration: {e}", "error")
            messagebox.showerror(
                "Error", f"Failed to export configuration: {e}")

    def export_offline_installer(self):
        if self.testing:
            return
        temp_dir = None
        try:
            save_dir = filedialog.askdirectory(
                title="Select Directory for Offline Installer")
            if not save_dir:
                return

            local_path = os.path.dirname(os.path.abspath(__file__))
            install_script = os.path.join(local_path, "install.sh")

            if not os.path.exists(install_script):
                if not self.ssh_client:
                    messagebox.showerror(
                        "Error",
                        "install.sh not found locally. "
                        "Connect via SSH to download it.")
                    return

                self.log_message("Downloading install.sh from server...")
                temp_dir = tempfile.mkdtemp()
                try:
                    self.ssh_client.exec_command(
                        "mkdir -p /tmp/glftpd-installer")
                    install_script = os.path.join(temp_dir, "install.sh")
                    self.sftp_client.get(
                        "/tmp/glftpd-installer/install.sh", install_script)
                except Exception as e:
                    shutil.rmtree(temp_dir, ignore_errors=True)
                    messagebox.showerror(
                        "Error", f"Failed to download install.sh: {e}")
                    return

            zip_path = os.path.join(save_dir,
                                    "glftpd-offline-installer.zip")
            with zipfile.ZipFile(zip_path, "w",
                                 zipfile.ZIP_DEFLATED) as zf:
                zf.write(install_script, "install.sh")

                with tempfile.NamedTemporaryFile(
                        mode="w", suffix=".cache", delete=False) as tmp:
                    tmp.write(self.generate_cache_content())
                    cache_tmp = tmp.name
                try:
                    zf.write(cache_tmp, "install.cache")
                finally:
                    os.unlink(cache_tmp)

                zf.writestr("README.txt",
                    "GLFTPD OFFLINE INSTALLER\n"
                    "============================\n\n"
                    "This package contains everything needed for an "
                    "unattended installation of glFTPd.\n\n"
                    "Instructions:\n"
                    "1. Extract the contents of this zip file "
                    "to the target server\n"
                    "2. Make install.sh executable: "
                    "chmod +x install.sh\n"
                    "3. Run the installation as root: "
                    "sudo ./install.sh\n\n"
                    "The installation will proceed unattended using "
                    "the configuration in install.cache.\n")

            if temp_dir:
                shutil.rmtree(temp_dir, ignore_errors=True)

            self.log_message(
                f"Offline installer exported to {zip_path}", "success")
        except Exception as e:
            if temp_dir:
                shutil.rmtree(temp_dir, ignore_errors=True)
            self.log_message(
                f"Error exporting offline installer: {e}", "error")
            messagebox.showerror(
                "Error", f"Failed to export offline installer: {e}")

    # -- Cache generation -------------------------------------------------------

    def generate_cache_content(self):
        lines = []
        for entry in CACHE_SCHEMA:
            if len(entry) == 1 and entry[0] == _SECTIONS_MARKER:
                for i, sec in enumerate(self.section_entries, 1):
                    lines.append(
                        f'section{i}="{sec["name"].get()}" '
                        f'# Name of section {i}')
                    lines.append(
                        f'section{i}dated="{sec["dated"].get()}" '
                        f'# Dated section?')
                for i, sec in enumerate(self.section_entries, 1):
                    lines.append(
                        f'sectionpath{i}="{sec["path"].get()}" '
                        f'# Path for section {i}')
            elif len(entry) == 1:
                lines.append(entry[0])
            else:
                key, attr, comment = entry
                val = getattr(self, attr).get()
                lines.append(f'{key}="{val}" # {comment}')
        return "\n".join(lines) + "\n"


def main():
    root = tk.Tk()
    GlftpdInstallerGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
